# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-27 03:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_auto_20181027_0913'),
        ('show', '0002_auto_20181025_2207'),
    ]

    operations = [
    ]
