# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-28 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0003_merge_20181027_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='classes',
            field=models.CharField(default=None, max_length=5, verbose_name='课时'),
        ),
        migrations.AddField(
            model_name='class',
            name='days',
            field=models.CharField(default=None, max_length=5, verbose_name='天数'),
        ),
    ]
