# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-28 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0004_auto_20181028_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='image',
            field=models.ImageField(max_length=256, upload_to='class', verbose_name='课程图片'),
        ),
    ]
