# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-28 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0005_auto_20181028_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=50, verbose_name='课程名称'),
        ),
    ]
