# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-28 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0006_auto_20181028_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='desc',
            field=models.CharField(max_length=256, verbose_name='课程描述'),
        ),
    ]
